"""Add reminder tables and client email

Revision ID: 9bf675d3057d
Revises: 
Create Date: 2026-07-24 19:16:44.076331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf675d3057d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_oauth_token', sa.Text(), nullable=True),
    sa.Column('gmail_authorized_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_settings_id'), 'reminder_settings', ['id'], unique=False)
    op.create_table('reminder_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('default_days_before', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_types_code'), 'reminder_types', ['code'], unique=True)
    op.create_index(op.f('ix_reminder_types_id'), 'reminder_types', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_types_name'), 'reminder_types', ['name'], unique=True)
    op.create_table('scheduler_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reminders_checked', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('emails_failed', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('trigger_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_runs_id'), 'scheduler_runs', ['id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reminder_type_id'], ['reminder_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type_id', sa.Integer(), nullable=False),
    sa.Column('first_due_date', sa.DateTime(), nullable=False),
    sa.Column('current_due_date', sa.DateTime(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('reminder_offsets', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('month_of_year', sa.Integer(), nullable=True),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reminder_type_id'], ['reminder_types.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_table('email_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('reminder_type_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_histories_id'), 'email_histories', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('current_due_date', sa.DateTime(), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_send_date', sa.DateTime(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id', 'current_due_date', 'offset_days', 'recipient_email', 'template_id', 'channel', name='uq_notification_identity')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_constraint(op.f('audit_logs_client_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('category_rules_client_id_fkey'), 'category_rules', type_='foreignkey')
    op.create_foreign_key(None, 'category_rules', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('client_bank_accounts_client_id_fkey'), 'client_bank_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'client_bank_accounts', 'clients', ['client_id'], ['id'])
    op.add_column('clients', sa.Column('email', sa.String(), nullable=True))
    op.drop_constraint(op.f('clients_business_name_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('journal_entries_client_id_fkey'), 'journal_entries', type_='foreignkey')
    op.drop_constraint(op.f('journal_entries_transaction_id_fkey'), 'journal_entries', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entries', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'journal_entries', 'transactions', ['transaction_id'], ['id'])
    op.drop_constraint(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', type_='foreignkey')
    op.create_foreign_key(None, 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint(op.f('transactions_client_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_account_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'client_bank_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_account_id_fkey'), 'transactions', 'client_bank_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('transactions_client_id_fkey'), 'transactions', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'journal_lines', type_='foreignkey')
    op.create_foreign_key(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.create_foreign_key(op.f('journal_entries_transaction_id_fkey'), 'journal_entries', 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('journal_entries_client_id_fkey'), 'journal_entries', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('clients_business_name_key'), 'clients', ['business_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('clients', 'email')
    op.drop_constraint(None, 'client_bank_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('client_bank_accounts_client_id_fkey'), 'client_bank_accounts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'category_rules', type_='foreignkey')
    op.create_foreign_key(op.f('category_rules_client_id_fkey'), 'category_rules', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('audit_logs_client_id_fkey'), 'audit_logs', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_email_histories_id'), table_name='email_histories')
    op.drop_table('email_histories')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_scheduler_runs_id'), table_name='scheduler_runs')
    op.drop_table('scheduler_runs')
    op.drop_index(op.f('ix_reminder_types_name'), table_name='reminder_types')
    op.drop_index(op.f('ix_reminder_types_id'), table_name='reminder_types')
    op.drop_index(op.f('ix_reminder_types_code'), table_name='reminder_types')
    op.drop_table('reminder_types')
    op.drop_index(op.f('ix_reminder_settings_id'), table_name='reminder_settings')
    op.drop_table('reminder_settings')
    # ### end Alembic commands ###
